- name: Configure containers on app server
  hosts: appserver
  connection: ssh
  become: true

  tasks:
    # Setup secrets so containers can have access to GCP resources 
    - name: Create secrets directory
      file:
        path: "/srv/secrets"
        state: "directory"
        mode: 0755 # Change to 0700
    - name: Copy service account key file
      copy:
        src: ../secrets/gcp-service.json
        dest: "/srv/secrets/gcp-service.json"
        mode: 0644
    - name: Authenticate gcloud using service account
      shell: "gcloud auth activate-service-account --key-file /srv/secrets/gcp-service.json"
    
    # Create common network for all containers
    - name: Create network
      docker_network:
          name: "{{docker_network_name}}"
          driver: "bridge"
          attachable: "yes"

    # in order to use this, after running the "deploy-docker-images.yml", need to get the stdout and replace that in the .docker-tag folder
    - name: Copy docker tag file
      copy:
        src: .docker-tag
        dest: .docker-tag
        mode: 0644
    - name: "Get docker tag"
      shell: "cat .docker-tag"
      register: tag
    - name: Print tag
      debug:
        var: tag
    - name: Create frontend container
      docker_container:
        name: "frontend"
        image: "gcr.io/{{ gcp_project }}/crypto-forecasting-frontend-react:{{ tag.stdout}}"
        state: started
        recreate: yes
        pull: yes
        restart: yes
        published_ports:
          - 3000:80
        networks:
          - name: "{{docker_network_name}}"

    # Create a folder on persistent disk for db data
    - name: Create data directory
      file:
        path: "/mnt/disk-1/data" # can see this when SSHing into VM with "sudo ls /mnt/disk-1/data"
        state: "directory"
        mode: 0777
    - name: Create persistent directory
      file:
        path: "/mnt/disk-1/persistent" # can see this when SSHing into VM with "sudo ls /mnt/disk-1/persistent"
        state: "directory"
        mode: 0777
    - name: Create secrets directory
      file:
        path: "/conf/secrets"
        state: "directory"
        mode: 0777

    # Create Postgress DB container
    - name: Create postgres container
      docker_container:
        name: "postgres"
        image: "postgres:latest"
        state: started
        recreate: yes
        published_ports:
          - 5432:5432
        env:
          POSTGRES_USER: "cryp"
          POSTGRES_PASSWORD: "bros"
          POSTGRES_DB: "crypbrosdb"
        networks:
          - name: "{{docker_network_name}}"
        volumes:
          - /mnt/disk-1/data:/var/lib/postgresql/data # Data folder in persistent drive; can view this on the VM
  
    - name: Copy db migration scripts
      copy:
        src: "/database-server/db"
        dest: "/conf"
    
    # don't have this yet for modeling
    # - name: Copy secrets file
    #   copy:
    #     src: "/secrets/bucket-reader.json"
    #     dest: "/conf/secrets/bucket-reader.json"

    # I needed to have this run on port 5432 or else I was getting an error ("Error: dial tcp 172.19.0.3:5436: connect: connection refused"); checked this by running "sudo docker container ls" on the VM and looking at the PORTS section, where it was giving 5432/tcp
    - name: Run DB migrations using dbmate
      shell: docker run --rm -it -v /conf/db:/db -e DATABASE_URL=postgres://cryp:bros@postgres:5432/crypbrosdb?sslmode=disable --network "{{docker_network_name}}" amacneil/dbmate up

    - name: Create api-service container
      docker_container:
        name: "api-service"
        image: "gcr.io/{{ gcp_project }}/crypto-forecasting-api-service:{{ tag.stdout}}"
        state: started
        recreate: yes # how is this recreation happening here?
        published_ports:
          - 9600:9000
        # environment variables can be added here or the Dockerfile
        env:
          DATABASE_URL: "postgres://cryp:bros@postgres:5432/crypbrosdb"
          GOOGLE_APPLICATION_CREDENTIALS: "/app/secrets/bucket-reader.json" 
          GCP_PROJECT: "crypto-forecasting-app"
          GCP_ZONE: "us-central1-a"
          GCS_BUCKET: "crypto-forecasting-bucket"
        networks:
          - name: "{{docker_network_name}}"
        volumes:
          - /mnt/disk-1/persistent:/persistent # we're mounting this container to the persistent disk
          - /conf/secrets:/secrets
  
    - name: Create worker-service container
      docker_container:
        name: "worker-service"
        image: "gcr.io/{{ gcp_project }}/crypto-forecasting-worker-service:{{ tag.stdout}}"
        state: started
        recreate: yes # how is this recreation happening here?
        # environment variables can be added here or the Dockerfile
        env:
          DATABASE_URL: "postgres://cryp:bros@postgres:5432/crypbrosdb"
          GOOGLE_APPLICATION_CREDENTIALS: "/app/secrets/bucket-reader.json"
          GCP_PROJECT: "crypto-forecasting-app"
          GCP_ZONE: "us-central1-a"
          GCS_BUCKET: "crypto-forecasting-bucket"
          # MODE: "worker" # don't need this anymore as we updated worker-service/docker-entrypoint.sh
        networks:
          - name: "{{docker_network_name}}"
        volumes:
          - /mnt/disk-1/persistent:/persistent # we're mounting this container to the persistent disk
          - /conf/secrets:/secrets
  

    - name: Check if containers are running
      shell: docker ps
    
    - name: "Remove all unused containers"
      shell: docker system prune -a -f
