exclude_x = ['NA', 'Open Time', 'Close Time', 'y', 'Date']

val_split, test_split = None, None

log_transformation_feat = ['Open Price', 'High price', 'Low Price', 'Close Price', 'Volume Traded',
                           'Quote asset Volume', 'Number of Trades', 'Taker buy base asset volume',
                           'Taker buy quote asset volume', 'Mid Price', 'Open Price_prev', 'Close Price_prev',
                           'Mid Price_prev', 'high_low', 'high_close', 'high_open', 'open_low', 'spread',
                           'rolling_avg_high_low_1h', 'rolling_avg_high_low_1d', 'rolling_avg_high_low_1w',
                           'rolling_avg_high_low_1m', 'rolling_max_high_low_1h',
                           'rolling_max_high_low_1d', 'rolling_max_high_low_1w', 'rolling_max_high_low_1m',
                           'rolling_avg_high_close_1h', 'rolling_avg_high_close_1d', 'rolling_avg_high_close_1w',
                           'rolling_avg_high_close_1m', 'rolling_max_high_close_1h', 'rolling_max_high_close_1d',
                           'rolling_max_high_close_1w', 'rolling_max_high_close_1m', 'rolling_avg_high_open_1h',
                           'rolling_avg_high_open_1d', 'rolling_avg_high_open_1w', 'rolling_avg_high_open_1m',
                           'rolling_max_high_open_1h', 'rolling_max_high_open_1d',
                           'rolling_max_high_open_1w', 'rolling_max_high_open_1m', 'rolling_avg_open_low_1h',
                           'rolling_avg_open_low_1d',
                           'rolling_avg_open_low_1w', 'rolling_avg_open_low_1m', 'rolling_max_open_low_1h',
                           'rolling_max_open_low_1d',
                           'rolling_max_open_low_1w', 'rolling_max_open_low_1m', 'rolling_avg_spread_1h',
                           'rolling_avg_spread_1d',
                           'rolling_avg_spread_1w', 'rolling_avg_spread_1m', 'rolling_max_spread_1h',
                           'rolling_max_spread_1d', 'rolling_max_spread_1w',
                           'rolling_max_spread_1m', 'rolling_avg_Open Price_1h', 'rolling_avg_Open Price_1d',
                           'rolling_avg_Open Price_1w', 'rolling_avg_Open Price_1m',
                           'rolling_max_Open Price_1h', 'rolling_max_Open Price_1d', 'rolling_max_Open Price_1w',
                           'rolling_max_Open Price_1m',
                           'rolling_avg_High price_1h', 'rolling_avg_High price_1d', 'rolling_avg_High price_1w',
                           'rolling_avg_High price_1m',
                           'rolling_max_High price_1h', 'rolling_max_High price_1d', 'rolling_max_High price_1w',
                           'rolling_max_High price_1m',
                           'rolling_avg_Low Price_1h', 'rolling_avg_Low Price_1d', 'rolling_avg_Low Price_1w',
                           'rolling_avg_Low Price_1m',
                           'rolling_max_Low Price_1h', 'rolling_max_Low Price_1d', 'rolling_max_Low Price_1w',
                           'rolling_max_Low Price_1m',
                           'rolling_avg_Close Price_1h', 'rolling_avg_Close Price_1d', 'rolling_avg_Close Price_1w',
                           'rolling_avg_Close Price_1m',
                           'rolling_max_Close Price_1h', 'rolling_max_Close Price_1d', 'rolling_max_Close Price_1w',
                           'rolling_max_Close Price_1m']

continuous_features = ['Open Price', 'High price', 'Low Price', 'Close Price', 'Volume Traded',
                       'Quote asset Volume', 'Number of Trades', 'Taker buy base asset volume',
                       'Taker buy quote asset volume', 'Mid Price', 'Open Price_prev', 'Close Price_prev',
                       'Mid Price_prev', 'high_low', 'high_close', 'high_open', 'open_low', 'spread',
                       'rolling_avg_high_low_1h', 'rolling_avg_high_low_1d', 'rolling_avg_high_low_1w',
                       'rolling_avg_high_low_1m', 'rolling_max_high_low_1h',
                       'rolling_max_high_low_1d', 'rolling_max_high_low_1w', 'rolling_max_high_low_1m',
                       'rolling_min_high_low_1h', 'rolling_min_high_low_1d',
                       'rolling_min_high_low_1w', 'rolling_min_high_low_1m', 'rolling_avg_high_close_1h',
                       'rolling_avg_high_close_1d', 'rolling_avg_high_close_1w', 'rolling_avg_high_close_1m',
                       'rolling_max_high_close_1h', 'rolling_max_high_close_1d', 'rolling_max_high_close_1w',
                       'rolling_max_high_close_1m', 'rolling_min_high_close_1h', 'rolling_min_high_close_1d',
                       'rolling_min_high_close_1w', 'rolling_min_high_close_1m', 'rolling_avg_high_open_1h',
                       'rolling_avg_high_open_1d', 'rolling_avg_high_open_1w', 'rolling_avg_high_open_1m',
                       'rolling_max_high_open_1h', 'rolling_max_high_open_1d',
                       'rolling_max_high_open_1w', 'rolling_max_high_open_1m', 'rolling_min_high_open_1h',
                       'rolling_min_high_open_1d',
                       'rolling_min_high_open_1w', 'rolling_min_high_open_1m', 'rolling_avg_open_low_1h',
                       'rolling_avg_open_low_1d',
                       'rolling_avg_open_low_1w', 'rolling_avg_open_low_1m', 'rolling_max_open_low_1h',
                       'rolling_max_open_low_1d',
                       'rolling_max_open_low_1w', 'rolling_max_open_low_1m', 'rolling_min_open_low_1h',
                       'rolling_min_open_low_1d',
                       'rolling_min_open_low_1w', 'rolling_min_open_low_1m', 'rolling_avg_spread_1h',
                       'rolling_avg_spread_1d',
                       'rolling_avg_spread_1w', 'rolling_avg_spread_1m', 'rolling_max_spread_1h',
                       'rolling_max_spread_1d', 'rolling_max_spread_1w',
                       'rolling_max_spread_1m', 'rolling_min_spread_1h', 'rolling_min_spread_1d',
                       'rolling_min_spread_1w', 'rolling_min_spread_1m',
                       'rolling_avg_Open Price_1h', 'rolling_avg_Open Price_1d', 'rolling_avg_Open Price_1w',
                       'rolling_avg_Open Price_1m',
                       'rolling_max_Open Price_1h', 'rolling_max_Open Price_1d', 'rolling_max_Open Price_1w',
                       'rolling_max_Open Price_1m',
                       'rolling_min_Open Price_1h', 'rolling_min_Open Price_1d', 'rolling_min_Open Price_1w',
                       'rolling_min_Open Price_1m',
                       'rolling_avg_High price_1h', 'rolling_avg_High price_1d', 'rolling_avg_High price_1w',
                       'rolling_avg_High price_1m',
                       'rolling_max_High price_1h', 'rolling_max_High price_1d', 'rolling_max_High price_1w',
                       'rolling_max_High price_1m',
                       'rolling_min_High price_1h', 'rolling_min_High price_1d', 'rolling_min_High price_1w',
                       'rolling_min_High price_1m',
                       'rolling_avg_Low Price_1h', 'rolling_avg_Low Price_1d', 'rolling_avg_Low Price_1w',
                       'rolling_avg_Low Price_1m',
                       'rolling_max_Low Price_1h', 'rolling_max_Low Price_1d', 'rolling_max_Low Price_1w',
                       'rolling_max_Low Price_1m',
                       'rolling_min_Low Price_1h', 'rolling_min_Low Price_1d', 'rolling_min_Low Price_1w',
                       'rolling_min_Low Price_1m',
                       'rolling_avg_Close Price_1h', 'rolling_avg_Close Price_1d', 'rolling_avg_Close Price_1w',
                       'rolling_avg_Close Price_1m',
                       'rolling_max_Close Price_1h', 'rolling_max_Close Price_1d', 'rolling_max_Close Price_1w',
                       'rolling_max_Close Price_1m',
                       'rolling_min_Close Price_1h', 'rolling_min_Close Price_1d', 'rolling_min_Close Price_1w',
                       'rolling_min_Close Price_1m']
